name: Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
  
    -
      name: Checkout
      uses: actions/checkout@v4

    
    - 
      name: Docker Metadata action
      uses: docker/metadata-action@v5.3.0
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        # set latest tag for master branch
        flavor: latest=true
        tags: |
          
          type=edge,branch=main,prefix=,suffix=
          type=ref,event=branch,prefix=,suffix=
          type=ref,event=pr,prefix=,suffix=
          type=semver,pattern={{version}},prefix=,suffix=
          
    
    - 
      name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
    
    # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            kxwell/ceg3120:latest
            kxwell/ceg3120:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}          
  redeploy:
    name: Redeploy - Webhook call
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
